sudo: required
services:
- docker
env:
  global:
    # Ensure the downloaded SDK is first on the PATH
    - PATH=${HOME}/google-cloud-sdk/bin:$PATH
    # Ensure the install happens without prompts
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: node_js
node_js:
- '6'
before_install:
- npm install grunt-cli -g
install:
- openssl aes-256-cbc -K $encrypted_669777908d02_key -iv $encrypted_669777908d02_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- mv keys.js config/keys.js
- mv cert.pem config/cert.pem
- mv key.pem config/key.pem
- rm gc_cred.json
- npm install
- docker build -t cloudboost/user-service:2.0.$TRAVIS_BUILD_NUMBER .
- docker build -t cloudboost/user-service:latest .
after_success:
#Deploy. 
#Docker Login
- openssl aes-256-cbc -K $encrypted_669777908d02_key -iv $encrypted_669777908d02_iv -in credentials.tar.enc -out credentials.tar -d
- tar -xvf credentials.tar
- docker login --username $DOCKERUSERNAME --password $DOCKERPASSWORD --email $DOCKEREMAIL
# Make sure SDK is downloaded - cache once it's working
- curl https://sdk.cloud.google.com | bash;
# List the SDK contents to ensure it's downloaded
- ls -l ${HOME}/google-cloud-sdk/bin
# Ensure the correct gcloud is being used
- which gcloud
# Print the gcloud version and make sure it's something
- gcloud --version
- ls
#Activate Google Cloud SDK with your project
- gcloud auth activate-service-account --key-file gc_cred.json
#Install Kubectl
- gcloud components install kubectl
- cwd=$(pwd)
- auth_file="$cwd/gc_cred.json"
- gcloud beta auth application-default login
- gcloud container clusters get-credentials $GOOGLECLUSTERNAME --zone $GOOGLEZONE --project $GOOGLEPROJECT
#Push docker images. 
- docker push cloudboost/user-service:2.0.$TRAVIS_BUILD_NUMBER
- docker push cloudboost/user-service:latest
#Upload to Kubernetes for deployment.
- kubectl rolling-update cloudboost-user-service --image=cloudboost/user-service:latest --image-pull-policy=Always

